---
# Basic structure
- name: ToDaMoon
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Create SecGrp
    ec2_group:
      name: ansible
      Description: "Risepic Security Group"
      region: "{{aws_region}}"
      vpc_id: "{{vpc_id}}"
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      rules:
        - proto: all
          cidr_ip: "{{my_local_cidr_ip}}"
        - proto: all
          group_name: ansible
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
    register: firewall

  - name: Clone Alpha Repo
    git:
      repo: https://github.com/Risepic/Alpha.git
      dest: /dest/risepic-alpha
      clone: yes
      update: yes


  - name: Create S3 Alpha bucket.
    local_action:
      module: s3
      bucket: 'risepic-alpha-bucket'
      mode: create
      aws_access_key: "{{aws_access_key}}"
      aws_secret_key: "{{aws_secret_key}}"
      key_name: "{{key_name}}"
      region: "{{aws_region}}"
      group_id: "{{firewall.group_id}}"
      mode: create
  - name: Sync git repo with S3 Bucket
    s3_sync:
      bucket: risepic-alpha-bucket
      file_root: /dest/risepic-alpha
      src: 
      mode: put
      metadata: 'Content-Encoding=gzip,Cache-Control=no-cache'
